coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 10%
        base: auto 
        flags: 
          - unit
        paths: 
          - "src"
       # advanced settings
        if_ci_failed: error #success, failure, error, ignore
        informational: false
        only_pulls: true